const games = [
  {
    id: 1,
    name: "Blox Fruits",
    subtitle: "🍍",
    icon: "/logo/blox.png",
    bgImage: "/logo/bloxmain.png",
    gradient: "linear-gradient(90deg, #41A7FF, #D9EDFF)",
    route: "/BloxFruits",
    color: "#41A7FF",
  },
  {
    id: 2,
    name: "Murder Mystery 2",
    subtitle: "🔪",
    icon: "/logo/murder.png",
    bgImage: "/logo/murdermain.png",
    gradient: "linear-gradient(90deg, #E90303, #FFA3A3)",
    route: "/murderMystery",
    color: "#E90303",
  },
  {
    id: 3,
    name: "Adopt Me!",
    subtitle: "🐾",
    icon: "/logo/adopt.png",
    bgImage: "/logo/adoptmain.png",
    gradient: "linear-gradient(90deg, #F7FE49, #D9EDFF)",
    route: "/AdoptMe",
    color: "#F9FF41",
  },
  {
    id: 4,
    name: "Blade Ball",
    subtitle: "⚔️",
    icon: "/logo/blade.png",
    bgImage: "/logo/blademain.png",
    gradient: "linear-gradient(90deg, #FF41A3, #D9EDFF)",
    route: "/BladeBall",
    color: "#FF41A3",
  },
  {
    id: 5,
    name: "Steal A Brainrot",
    subtitle: "💎",
    icon: "/logo/steal.png",
    bgImage: "/logo/stealmain.png",
    gradient: "linear-gradient(90deg, #A641FF, #D9EDFF)",
    route: "/StealABrainrot",
    color: "#A641FF",
  },
  {
    id: 6,
    name: "Grow A Garden",
    subtitle: "🌱",
    icon: "/logo/grow.png",
    bgImage: "/logo/growmain.png",
    gradient: "linear-gradient(90deg, #2ECC71, #27AE60)",
    route: "/GrowAGarden",
    color: "#3DFF88",
  },
  {
    id: 7,
    name: "Plant vs Brainrot",
    subtitle: "🌿",
    icon: "/logo/grow.png",
    bgImage: "/logo/growmain.png",
    gradient: "linear-gradient(90deg, #FF8132, #E9E9E9)",
    route: "/PlantVsBrainrot",
    color: "#FF8132",
  },
  {
    id: 8,
    name: "Dress To Impress",
    subtitle: "👗",
    icon: "/logo/impress.png",
    bgImage: "/logo/impressmain.png",
    gradient: "linear-gradient(90deg, #FF327D, #E9E9E9)",
    route: "/DressToImpress",
    color: "#FF327D",
  },
  {
    id: 9,
    name: "99 nights in the forest",
    subtitle: "🌳",
    icon: "/logo/99.png",
    bgImage: "/logo/99main.png",
    gradient: "linear-gradient(90deg, #FF9832, #E9E9E9)",
    route: "/99NightsInTheForest",
    color: "#FF9832",
  },
];

export { games };
