import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";

const poppinsFont = Poppins({
  variable: "--font-poppins",
  weight: ["600", "500", "400", "700"],
});

const interFont = Inter({
  variable: "--font-inter",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppinsFont.variable} ${interFont.variable} antialiased max-w-full mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
